### ISSUE TITLE
Widgets in sidebars get messed up through switching

### ISSUE THREAD

**Issue by lmoffereins** [nash-ye/WP-Conditional-Themes#3]
When switching between themes, the registered widgets in sidebars are removed and tossed around. WP apparently does a bad job remembering which widgets belong with which theme's sidebars. I haven't looked into it yet, but is there any chance the widgets can be brought back in their right position when toggling through themes? 

It would be great if this plugin would allow for per-theme widget positions (and settings!), so one could setup a switched theme's details in the admin, while the other theme's compositions remain intact.

**Comment by lmoffereins** [comment]
I found that the issue is with updating widgets when using the switched theme. Since the registered widgets are theme-dependent, both getting and updating widgets has to be filtered. In your plugin, only the getting part is covered.

I have fixed this with filtering the `pre_update_option_sidebars_widgets` filter. You can view my implementation in my [Theme Switcher plugin](https://github.com/lmoffereins/theme-switcher/commit/48e08c06d0a517e509dcedeaee3b8c9836de2c5b).

**Comment by nash-ye** [comment]
Thank you!. I had never got an enough time to look into this, I will include your solution with your name in the next update.
